### ISSUE TITLE
Handle when API is under maintenance

### ISSUE THREAD

**Issue by benda95280** [sywesk/ocea-exporter#1]
Dear,

It seems it do not support when Ocea API is under maintenance : 
`2024-05-01T16:18:39.054Z FATAL ocea-exporter/main.go:37 failed to start counter fetcher {"error": "failed to fetch initial state: failed to get resident: failed to get resident: HTTP request failed: invalid status code 502 (502 Bad Gateway)"}`

The API today return : 
`{
  "IsOnline": false,
  "MaintenancePageUrl": "https://imagocorewafprod.blob.core.windows.net/maintenance/app-offline-espace-resident.htm",
  "ErrorMessage": "The service is under maintenance"
}`

Thanks a lot for this ! It seems to be the only tool which exist :)

**Comment by sywesk** [comment]
Thanks for your kind words! I'll look into this ASAP 🙏

**Comment by sywesk** [comment]
It should be done now, fixed in v0.4.1 :)
